### ISSUE TITLE
usercomment

### ISSUE THREAD

**Issue by mythodeia** [Nikita2k/SimpleExif#1]
Hello,
according to [this](http://www.exif.org/Exif2-2.PDF) page if you search with usercomment you will see that it accepts ascii-unicode-jis. if i try to add a Greek word in the kCGImagePropertyExifUserComment it does not recognise the whole word when you preview the exif in the image inspector (mac).

Do you have any idea how to add that character code to the string so it can be recognized?

if you want to try use this word `Ελληνικά`

thanks

**Comment by Nikita2k** [comment]
I'm afraid there is not solution, because it seems to be a bug in Framework.
See this question as a [reference](http://stackoverflow.com/questions/16321502/how-do-you-write-the-degrees-symbol-into-exif-on-ios)

**Comment by mythodeia** [comment]
thanks for your response. i figured it out by using the exiftool on my mac and saw the ASCII value ImageIO adds on the image. too bad..after all these years 
anyway.. thanks again
