### ISSUE TITLE
It does not work 

### ISSUE THREAD

**Issue by junestchick** [Nikita2k/SimpleExif#6]
I use AVfoundation to take image then use simpleExif to write location infor and send image to server. But the server side cannot read location infor from image.

**Comment by Nikita2k** [comment]
Have you tried saving images to app sandbox and view them with Preview? Lets make sure problem is not on server side

**Comment by junestchick** [comment]
I upload image to server then try to save and open with preview, it shows no location. This is my code on client :
`let rotatedImage = rotateImage(image)
        if let location = currentLocation {
            let exif = ExifContainer()
            exif.addDescription("Developed by Unima")
            exif.addLocation(location)
            rotatedImage.addExif(exif)
        }
        self.imageStore.append(ImageModel(name: "VA", image: rotatedImage, location: currentLocation))`

Then I convert image to NSdata and upload it:
`let imageData = UIImageJPEGRepresentation(image.image!, 1)
                let uploadService = VAClientService()
                GCDCommon.serialQueue({ 
                    uploadService.uploadImageWithCode(codeID, imageName: image.name, imageData: imageData, complection: { (success, error) in
                        if success {
                            image.uploaded = true
                            VAVideoCallingManager.shared.sendSignalWithType(SignalType.UploadedPhoto, andMessage: "Hello, A new photo just uploaded. Pls reload page to see.")
                        }
                    })
                })`
And wrongs ?

**Comment by junestchick** [comment]
Hi, the problem is solved. UIImageJPEGRepresentation makes lost metadata infor of image. So I use another way and it works fine now. Thanks.

**Comment by Nikita2k** [comment]
Thanks for update! Closing
